<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class DaerahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('daerahs')->insert([
            ['negeri' => 'Johor', 'daerah' => 'Batu Pahat'],
            ['negeri' => 'Johor', 'daerah' => 'Johor Bahru'],
            ['negeri' => 'Johor', 'daerah' => 'Kluang'],
            ['negeri' => 'Johor', 'daerah' => 'Kota Tinggi'],
            ['negeri' => 'Johor', 'daerah' => 'Mersing'],
            ['negeri' => 'Johor', 'daerah' => 'Muar'],
            ['negeri' => 'Johor', 'daerah' => 'Pontian'],
            ['negeri' => 'Johor', 'daerah' => 'Segamat'],
            ['negeri' => 'Johor', 'daerah' => 'Kulai'],
            ['negeri' => 'Johor', 'daerah' => 'Tangkak'],
            ['negeri' => 'Kedah', 'daerah' => 'Baling'],
            ['negeri' => 'Kedah', 'daerah' => 'Bandar Baharu'],
            ['negeri' => 'Kedah', 'daerah' => 'Kota Setar'],
            ['negeri' => 'Kedah', 'daerah' => 'Kuala Muda'],
            ['negeri' => 'Kedah', 'daerah' => 'Kubang Pasu'],
            ['negeri' => 'Kedah', 'daerah' => 'Kulim'],
            ['negeri' => 'Kedah', 'daerah' => 'Langkawi'],
            ['negeri' => 'Kedah', 'daerah' => 'Padang Terap'],
            ['negeri' => 'Kedah', 'daerah' => 'Sik'],
            ['negeri' => 'Kedah', 'daerah' => 'Yan'],
            ['negeri' => 'Kedah', 'daerah' => 'Pendang'],
            ['negeri' => 'Kedah', 'daerah' => 'Pokok Sena'],
            ['negeri' => 'Kelantan', 'daerah' => 'Bachok'],
            ['negeri' => 'Kelantan', 'daerah' => 'Kota Bharu'],
            ['negeri' => 'Kelantan', 'daerah' => 'Machang'],
            ['negeri' => 'Kelantan', 'daerah' => 'Pasir Mas'],
            ['negeri' => 'Kelantan', 'daerah' => 'Pasir Puteh'],
            ['negeri' => 'Kelantan', 'daerah' => 'Tanah Merah'],
            ['negeri' => 'Kelantan', 'daerah' => 'Tumpat'],
            ['negeri' => 'Kelantan', 'daerah' => 'Gua Musang'],
            ['negeri' => 'Kelantan', 'daerah' => 'Kuala Krai'],
            ['negeri' => 'Kelantan', 'daerah' => 'Jeli'],
            ['negeri' => 'Kelantan', 'daerah' => 'Lojing'],
            ['negeri' => 'Melaka', 'daerah' => 'Alor Gajah (Melaka Utara)'],
            ['negeri' => 'Melaka', 'daerah' => 'Jasin (Melaka Selatan)'],
            ['negeri' => 'Melaka', 'daerah' => 'Melaka Tengah'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Jelebu'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Kuala Pilah'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Port Dickson'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Rembau'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Seremban'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Tampin'],
            ['negeri' => 'Negeri Sembilan', 'daerah' => 'Jempol'],
            ['negeri' => 'Pahang', 'daerah' => 'Bentong'],
            ['negeri' => 'Pahang', 'daerah' => 'Cameron Highlands'],
            ['negeri' => 'Pahang', 'daerah' => 'Jerantut'],
            ['negeri' => 'Pahang', 'daerah' => 'Kuantan'],
            ['negeri' => 'Pahang', 'daerah' => 'Lipis'],
            ['negeri' => 'Pahang', 'daerah' => 'Pekan'],
            ['negeri' => 'Pahang', 'daerah' => 'Raub'],
            ['negeri' => 'Pahang', 'daerah' => 'Temerloh'],
            ['negeri' => 'Pahang', 'daerah' => 'Rompin'],
            ['negeri' => 'Pahang', 'daerah' => 'Maran'],
            ['negeri' => 'Pahang', 'daerah' => 'Bera'],
            ['negeri' => 'Pulau Pinang', 'daerah' => 'Seberang Perai Tengah (Bukit Mertajam)'],
            ['negeri' => 'Pulau Pinang', 'daerah' => 'Seberang Perai Utara (Butterworth)'],
            ['negeri' => 'Pulau Pinang', 'daerah' => 'Seberang Perai Selatan (Nibong Tebal)'],
            ['negeri' => 'Pulau Pinang', 'daerah' => 'Timur Laut'],
            ['negeri' => 'Pulau Pinang', 'daerah' => 'Barat Daya'],
            ['negeri' => 'Perak', 'daerah' => 'Batang Padang'],
            ['negeri' => 'Perak', 'daerah' => 'Dinding (Manjung)'],
            ['negeri' => 'Perak', 'daerah' => 'Kinta'],
            ['negeri' => 'Perak', 'daerah' => 'Kerian'],
            ['negeri' => 'Perak', 'daerah' => 'Kuala Kangsar'],
            ['negeri' => 'Perak', 'daerah' => 'Larut & Matang'],
            ['negeri' => 'Perak', 'daerah' => 'Hilir Perak'],
            ['negeri' => 'Perak', 'daerah' => 'Hulu Perak'],
            ['negeri' => 'Perak', 'daerah' => 'Perak Tengah'],
            ['negeri' => 'Perak', 'daerah' => 'Kampar'],
            ['negeri' => 'Perak', 'daerah' => 'Muallim'],
            ['negeri' => 'Perak', 'daerah' => 'Bagan Datuk'],
            ['negeri' => 'Perak', 'daerah' => 'Selama'],
            ['negeri' => 'Selangor', 'daerah' => 'Gombak'],
            ['negeri' => 'Selangor', 'daerah' => 'Klang'],
            ['negeri' => 'Selangor', 'daerah' => 'Kuala Langat'],
            ['negeri' => 'Selangor', 'daerah' => 'Kuala Selangor'],
            ['negeri' => 'Selangor', 'daerah' => 'Petaling'],
            ['negeri' => 'Selangor', 'daerah' => 'Sabak Bernam'],
            ['negeri' => 'Selangor', 'daerah' => 'Sepang'],
            ['negeri' => 'Selangor', 'daerah' => 'Hulu Langat'],
            ['negeri' => 'Selangor', 'daerah' => 'Hulu Selangor'],
            ['negeri' => 'Terengganu', 'daerah' => 'Besut'],
            ['negeri' => 'Terengganu', 'daerah' => 'Dungun'],
            ['negeri' => 'Terengganu', 'daerah' => 'Kemaman'],
            ['negeri' => 'Terengganu', 'daerah' => 'Kuala Terengganu'],
            ['negeri' => 'Terengganu', 'daerah' => 'Marang'],
            ['negeri' => 'Terengganu', 'daerah' => 'Hulu Terengganu'],
            ['negeri' => 'Terengganu', 'daerah' => 'Setiu'],
            ['negeri' => 'Terengganu', 'daerah' => 'Kuala Nerus'],
            ['negeri' => 'Sabah', 'daerah' => 'Tawau'],
            ['negeri' => 'Sabah', 'daerah' => 'Lahad Datu'],
            ['negeri' => 'Sabah', 'daerah' => 'Semporna'],
            ['negeri' => 'Sabah', 'daerah' => 'Sandakan'],
            ['negeri' => 'Sabah', 'daerah' => 'Kinabatangan'],
            ['negeri' => 'Sabah', 'daerah' => 'Beluran'],
            ['negeri' => 'Sabah', 'daerah' => 'Kota Kinabalu'],
            ['negeri' => 'Sabah', 'daerah' => 'Ranau'],
            ['negeri' => 'Sabah', 'daerah' => 'Kota Belud'],
            ['negeri' => 'Sabah', 'daerah' => 'Tuaran'],
            ['negeri' => 'Sabah', 'daerah' => 'Penampang'],
            ['negeri' => 'Sabah', 'daerah' => 'Papar'],
            ['negeri' => 'Sabah', 'daerah' => 'Kudat'],
            ['negeri' => 'Sabah', 'daerah' => 'Kota Marudu'],
            ['negeri' => 'Sabah', 'daerah' => 'Pitas'],
            ['negeri' => 'Sabah', 'daerah' => 'Beaufort'],
            ['negeri' => 'Sabah', 'daerah' => 'Kuala Penyu'],
            ['negeri' => 'Sabah', 'daerah' => 'Sipitang'],
            ['negeri' => 'Sabah', 'daerah' => 'Tenom'],
            ['negeri' => 'Sabah', 'daerah' => 'Nabawan'],
            ['negeri' => 'Sabah', 'daerah' => 'Keningau'],
            ['negeri' => 'Sabah', 'daerah' => 'Tambunan'],
            ['negeri' => 'Sabah', 'daerah' => 'Kunak'],
            ['negeri' => 'Sabah', 'daerah' => 'Tongod'],
            ['negeri' => 'Sabah', 'daerah' => 'Putatan'],
            ['negeri' => 'Sabah', 'daerah' => 'Telupid'],
            ['negeri' => 'Sabah', 'daerah' => 'Kalabakan'],
            ['negeri' => 'Sarawak', 'daerah' => 'Kuching'],
            ['negeri' => 'Sarawak', 'daerah' => 'Bau'],
            ['negeri' => 'Sarawak', 'daerah' => 'Lundu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Samarahan'],
            ['negeri' => 'Sarawak', 'daerah' => 'Serian'],
            ['negeri' => 'Sarawak', 'daerah' => 'Simunjan (Hilir Sadong)'],
            ['negeri' => 'Sarawak', 'daerah' => 'Sri Aman (Simanggang)'],
            ['negeri' => 'Sarawak', 'daerah' => 'Lubok Antu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Betong (Saribas)'],
            ['negeri' => 'Sarawak', 'daerah' => 'Saratok (Kalaka)'],
            ['negeri' => 'Sarawak', 'daerah' => 'Sarikei'],
            ['negeri' => 'Sarawak', 'daerah' => 'Meradong'],
            ['negeri' => 'Sarawak', 'daerah' => 'Daro'],
            ['negeri' => 'Sarawak', 'daerah' => 'Julau'],
            ['negeri' => 'Sarawak', 'daerah' => 'Sibu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Dalat'],
            ['negeri' => 'Sarawak', 'daerah' => 'Mukah'],
            ['negeri' => 'Sarawak', 'daerah' => 'Kanowit'],
            ['negeri' => 'Sarawak', 'daerah' => 'Bintulu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Tatau'],
            ['negeri' => 'Sarawak', 'daerah' => 'Kapit'],
            ['negeri' => 'Sarawak', 'daerah' => 'Song'],
            ['negeri' => 'Sarawak', 'daerah' => 'Belaga'],
            ['negeri' => 'Sarawak', 'daerah' => 'Miri'],
            ['negeri' => 'Sarawak', 'daerah' => 'Marudi'],
            ['negeri' => 'Sarawak', 'daerah' => 'Limbang'],
            ['negeri' => 'Sarawak', 'daerah' => 'Lawas'],
            ['negeri' => 'Sarawak', 'daerah' => 'Matu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Asajaya'],
            ['negeri' => 'Sarawak', 'daerah' => 'Pakan'],
            ['negeri' => 'Sarawak', 'daerah' => 'Selangau'],
            ['negeri' => 'Sarawak', 'daerah' => 'Tebedu'],
            ['negeri' => 'Sarawak', 'daerah' => 'Pusa'],
            ['negeri' => 'Sarawak', 'daerah' => 'Kabong'],
            ['negeri' => 'Sarawak', 'daerah' => 'Tanjung Manis'],
            ['negeri' => 'Sarawak', 'daerah' => 'Sebauh'],
            ['negeri' => 'Sarawak', 'daerah' => 'Bukit Mabong'],
            ['negeri' => 'Sarawak', 'daerah' => 'Subis'],
            ['negeri' => 'Sarawak', 'daerah' => 'Beluru'],
            ['negeri' => 'Sarawak', 'daerah' => 'Telang Usan'],
        ]);
    }
}
